### ISSUE TITLE
Search dont work

### ISSUE THREAD

**Issue by helloworldguy4** [stevesoltys/duckduckgo#3]
This code dont work:
```
require 'duckduckgo'

results = DuckDuckGo::search(:query => 'Apples')
```
I always get this error then:

**C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:319:in `open_http'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/open_uri_redirections-0.2.1/lib/open-uri/redirections_patch.rb:55:in `open_uri'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:717:in `open'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:35:in `open'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/duckduckgo-0.1.5/lib/duckduckgo/search.rb:24:in `search'
        from C:/Users/LuckyChicken/Desktop/duckduckgo.rb:3:in `<main>'**

What should I do?

**Comment by stevesoltys** [comment]
This is not a problem with the gem, but rather with your Ruby environment.

I see you are on Windows, so a possible solution can be found here: http://stackoverflow.com/a/7536952

**Comment by helloworldguy4** [comment]
thank you! works
